import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import SubNavBar from '../components/SubNavBar'

function chats() {
    return (
        <div className="bg-default">
          <Head>
            <title>Task Management | Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          {/* Header */}
          <Header selectedTab="work" />
    
          {/* Tasks */}
          <div className='px-4 sm:px-6 md:px-8 lg:px-10 min-h-screen'>
            <h1 className="text-3xl font-bold mt-11">Projects</h1>
            <SubNavBar selectedTab="chats" />

          </div>
          {/* Modal */}
        </div>
    )
}

export default chats
