import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import HomePage from './homepage';
import { useState } from 'react'
import Task from '../components/Task'
import TaskColumn from '../components/TaskColumn'
import Project from '../components/Project'
import {faker} from "@faker-js/faker";
import SubNavBar from '../components/SubNavBar'
import Header from '../components/Header'

import {
  EnvelopeIcon,
  LockClosedIcon,
  EyeIcon,
  EyeSlashIcon
} from "@heroicons/react/24/outline"
export default function Home() {
  return (
    <div className="bg-default h-screen">
        <Head>
          <title>Task Management | Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Header */}
        <Header selectedTab="work" />

        {/* Tasks */}
        <div className='px-4 sm:px-6 md:px-8 lg:px-10 min-h-screen'>
        <h1 className="text-3xl font-bold mt-11">Projects</h1>
        <SubNavBar selectedTab="projects" />
        <div className="flex space-x-5 w-full overflow-x-scroll scroll-smooth scrollbar">
            <TaskColumn name="New Projects">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="To do" nCount="2">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="In Progress">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="Completed">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="Pending Client Review">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="Pending 3rd Party Action">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="Revision">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
            <TaskColumn name="Ready for review">
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
              <Project name="App Development" priority="low" taskNumber="2" profileImage={faker.image.avatar()} />
            </TaskColumn>
        </div>
        </div>
        {/* Modal */}
    </div>
  )









  // const [login, setLogin] = useState(false);
  // const [showPass, setShowPass] = useState(false)
  // return (
  //   <div className="bg-default h-screen">
  //     <Head>
  //       <title>Task Management | Admin</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <div className="grid grid-cols-12 h-screen">
  //       <div className="col-span-1 lg:col-span-3">

  //       </div>
  //       <div className="col-span-10 lg:col-span-5 flex flex-col items-center lg:px-10">
  //         <div className="relative w-36 h-24 mb-20 cursor-pointer mt-5">
  //           <Image src="/LOGO.png" layout="fill" alt="Profile" objectFit="contain" />
  //         </div>
  //         <p className="text-3xl font-bold pb-3 w-full text-center">Welcome Mrs. Donshay</p>
  //         <p className="text-gray-500">Login to continue using</p>
  //         <div className="pt-10 sm:px-10 w-full max-w-lg">
  //             <form action="/homepage" method="post">
  //               <div className="shadow-md flex justify-center items-center p-5 bg-white rounded mb-7">
  //                 <EnvelopeIcon className="w-6 h-6 text-gray-500" />
  //                 <input className="focus:outline-none pl-4 w-full" type="email" name="email" id="email" placeholder="Email" />
  //               </div>
  //               {
  //                 showPass ?
  //                   <div className="shadow-md flex justify-center items-center p-5 bg-white rounded">
  //                     <LockClosedIcon className="w-6 h-6 text-gray-500" />
  //                     <input className="focus:outline-none pl-4 w-full" type="text" name="password" id="password" placeholder="Password" />
  //                     <EyeIcon className='w-6 h-6 text-gray-500 hover:text-black cursor-pointer' onClick={()=>setShowPass(false)} />
  //                   </div>:
  //                   <div className="shadow-md flex justify-center items-center p-5 bg-white rounded">
  //                     <LockClosedIcon className="w-6 h-6 text-gray-500" />
  //                     <input className="focus:outline-none pl-4 w-full" type="password" name="password" id="password" placeholder="Password" />
  //                     <EyeSlashIcon className='w-6 h-6 text-gray-500 hover:text-black cursor-pointer' onClick={()=>setShowPass(true)} />
  //                   </div>
  //               }
  //               <Link href="#">
  //                 <p className="text-end w-full text-sm text-gray-500 mt-2 hover:text-black cursor-pointer">
  //                   Forgot Password?
  //                 </p>
  //               </Link>
  //               <input className="shadow-md flex justify-center items-center p-5 bg-[#004064] rounded mt-7 cursor-pointer text-white w-full" type="submit" value="Login" />
  //             </form>
  //         </div>
  //       </div>
  //       <div className="col-span-4 flex-col justify-center items-end h-full w-full hidden lg:flex">
  //         <div className="h-[48vh] aspect-square rounded-tl-full bg-[#81B3FF] flex justify-end items-end">
  //           <div className="h-[38vh] aspect-square rounded-tl-full bg-[#76ACFF] flex justify-end items-end">
  //             <div className="h-[28vh] aspect-square rounded-tl-full bg-[#65A3FF] flex justify-end items-end">
  //               <div className="h-[18vh] aspect-square rounded-tl-full bg-[#5A9CFF] flex justify-end items-end">
  //               </div>
  //             </div>
  //           </div>
  //         </div>
  //         <div className="h-[48vh] aspect-square rounded-bl-full bg-[#81B3FF] flex justify-end items-start">
  //           <div className="h-[38vh] aspect-square rounded-bl-full bg-[#76ACFF] flex justify-end items-start">
  //             <div className="h-[28vh] aspect-square rounded-bl-full bg-[#65A3FF] flex justify-end items-start">
  //               <div className="h-[18vh] aspect-square rounded-bl-full bg-[#5A9CFF] flex justify-end items-start">
  //               </div>
  //             </div>
  //           </div>
  //         </div>
  //       </div>
  //     </div>
  //   </div>
  // )
}
