import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import SubNavBar from '../components/SubNavBar'
import {
    MagnifyingGlassIcon,
    TrashIcon,
  } from "@heroicons/react/24/outline"
function users() {
    return (
        <div className="bg-default">
          <Head>
            <title>Task Management | Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          {/* Header */}
          <Header selectedTab="work" />
    
          {/* Tasks */}
          <div className='px-4 sm:px-6 md:px-8 lg:px-10 min-h-screen'>
            <h1 className="text-3xl font-bold mt-11">Projects</h1>
            <SubNavBar selectedTab="users" />
            <div className="mt-5 px-5 py-4 border border-gray-200 rounded-md flex">
                <MagnifyingGlassIcon className="h-7 w-7 mr-3" />
                <input type="text" className="bg-inherit w-full focus:outline-none" placeholder="Search user by email, username ..." />
            </div>
          </div>
          {/* Modal */}
        </div>
    )
}

export default users
